### ISSUE TITLE
Further clarification on random drop behaviors 

### ISSUE THREAD

**Issue by hideogump** [adjacentlink/emane#148]
EMANE drops packets on the receiver based on receiver power versus sensitivity.  However, this dropping also has a randomness to it, such that when the drop percentage should be 25 percent, the measured drop percentage over any given period of time has some randomness to it, sometimes more, sometimes less, perhaps when observed over several seconds it will average out to 25 percent.  

Can you provide a definitive statement on the random nature of packet drops based on say a fixed configuration of the elements used for rx power and rx sensitivity.

**Comment by ChengDaHaI** [comment]
I think your concerns is about how the PCR(Packet Completion Ratio) works. Since PCR gives a probability of  packet reception, your packet drop measurement (frequency) approachs the given probability but not be exactly the probability. This is the basic of Probability and Statistics. 

A related example is given in [EmaneTutorial](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-5).
